FROM openjdk:8

COPY . .
ENV TYRIONROOT
ENV SERVERMODE
ENV DATABASEURL
ENV DATABASEUSR
ENV DATABASEPASS
ENV SECURED
ENV DOMAIN
ENV CERTPATH
ENV CERTPASS
RUN chmod -R +x ./sbt-dist
RUN chmod +x ./sbt
RUN ./sbt compile
CMD ["./sbt", "run"]
